'use client';

import { useEffect, useState } from 'react';
import {
  collection,
  collectionGroup,
  getDocs,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  serverTimestamp
} from 'firebase/firestore';

import { db } from '@/lib/firebase';
import AdminLayout from '@/components/AdminLayout';
import { Plus, Trash2, ToggleLeft, ToggleRight, Bell } from 'lucide-react';

const severityOptions = ['low', 'medium', 'high'];
const typeOptions = ['rain', 'wind', 'heat', 'humidity', 'drought', 'general'];

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({
    title: '',
    subtitle: '',
    severity: 'medium',
    type: 'general',
    location: ''
  });
  const [saving, setSaving] = useState(false);

  // ✅ FIX: now pulls AI alerts from Firestore subcollections
  const fetchAlerts = async () => {
    setLoading(true);

    try {
      const snap = await getDocs(collectionGroup(db, 'alerts'));

      const data = snap.docs.map(d => {
        const alert = d.data() as any;

        return {
          id: d.id,
          ...alert,
          // 👇 recover owner of AI alert (users/{uid}/alerts)
          userId: d.ref.parent.parent?.id || null
        };
      });

      setAlerts(data);
    } catch (err) {
      console.error('Error fetching alerts:', err);
    }

    setLoading(false);
  };

  useEffect(() => {
    fetchAlerts();
  }, []);

  const addAlert = async () => {
    if (!form.title) return;
    setSaving(true);

    const ref = await addDoc(collection(db, 'alerts'), {
      ...form,
      active: true,
      autoGenerated: false,
      createdAt: serverTimestamp(),
    });

    setAlerts(prev => [
      ...prev,
      {
        id: ref.id,
        ...form,
        active: true,
        autoGenerated: false
      }
    ]);

    setForm({
      title: '',
      subtitle: '',
      severity: 'medium',
      type: 'general',
      location: ''
    });

    setShowForm(false);
    setSaving(false);
  };

  const toggleAlert = async (alertId: string, current: boolean) => {
    await updateDoc(doc(db, 'alerts', alertId), {
      active: !current
    });

    setAlerts(prev =>
      prev.map(a =>
        a.id === alertId ? { ...a, active: !current } : a
      )
    );
  };

  const deleteAlert = async (alertId: string) => {
    if (!confirm('Delete this alert?')) return;

    await deleteDoc(doc(db, 'alerts', alertId));

    setAlerts(prev => prev.filter(a => a.id !== alertId));
  };

  const severityColor = (s: string) => {
    if (s === 'high') return 'badge-red';
    if (s === 'medium') return 'badge-yellow';
    return 'badge-blue';
  };

  return (
    <AdminLayout>
      <div className="space-y-6">

        {/* HEADER */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="font-display text-2xl font-bold text-gray-900">
              Alerts
            </h1>
            <p className="text-gray-500 text-sm mt-1">
              {alerts.filter(a => a.active).length} active alerts
            </p>
          </div>

          <button
            onClick={() => setShowForm(true)}
            className="btn-primary flex items-center gap-2"
          >
            <Plus size={16} /> New Alert
          </button>
        </div>

        {/* FORM */}
        {showForm && (
          <div className="card p-6">
            <h3 className="font-semibold text-gray-900 mb-4">
              Create Alert
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">

              <input
                className="input"
                placeholder="Title"
                value={form.title}
                onChange={e =>
                  setForm(p => ({ ...p, title: e.target.value }))
                }
              />

              <input
                className="input"
                placeholder="Location"
                value={form.location}
                onChange={e =>
                  setForm(p => ({ ...p, location: e.target.value }))
                }
              />

              <input
                className="input sm:col-span-2"
                placeholder="Description"
                value={form.subtitle}
                onChange={e =>
                  setForm(p => ({ ...p, subtitle: e.target.value }))
                }
              />

              <select
                className="input"
                value={form.type}
                onChange={e =>
                  setForm(p => ({ ...p, type: e.target.value }))
                }
              >
                {typeOptions.map(t => (
                  <option key={t}>{t}</option>
                ))}
              </select>

              <select
                className="input"
                value={form.severity}
                onChange={e =>
                  setForm(p => ({ ...p, severity: e.target.value }))
                }
              >
                {severityOptions.map(s => (
                  <option key={s}>{s}</option>
                ))}
              </select>

            </div>

            <div className="flex gap-3 mt-4">
              <button
                onClick={addAlert}
                disabled={saving}
                className="btn-primary"
              >
                {saving ? 'Creating...' : 'Create Alert'}
              </button>

              <button
                onClick={() => setShowForm(false)}
                className="btn-secondary"
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {/* LIST */}
        <div className="space-y-3">

          {loading ? (
            <div className="card p-8 text-center text-gray-400">
              Loading alerts...
            </div>
          ) : alerts.length === 0 ? (
            <div className="card p-12 text-center">
              <Bell size={40} className="mx-auto text-gray-300 mb-3" />
              <p className="text-gray-500">No alerts yet.</p>
            </div>
          ) : (
            alerts.map(alert => (
              <div
                key={alert.id}
                className={`card p-4 flex items-start gap-4 ${
                  !alert.active ? 'opacity-60' : ''
                }`}
              >

                <div
                  className={`w-2 h-2 rounded-full mt-2 ${
                    alert.severity === 'high'
                      ? 'bg-red-500'
                      : alert.severity === 'medium'
                      ? 'bg-yellow-500'
                      : 'bg-blue-500'
                  }`}
                />

                <div className="flex-1">
                  <p className="font-medium">{alert.title}</p>

                  <div className="flex gap-2 text-xs mt-1">
                    <span className={severityColor(alert.severity)}>
                      {alert.severity}
                    </span>

                    <span className="badge-gray">{alert.type}</span>

                    {alert.autoGenerated && (
                      <span className="badge-blue">AI</span>
                    )}

                    {alert.userId && (
                      <span className="badge-gray">
                        user:{alert.userId.slice(0, 6)}
                      </span>
                    )}
                  </div>

                  {alert.subtitle && (
                    <p className="text-sm text-gray-500 mt-1">
                      {alert.subtitle}
                    </p>
                  )}
                </div>

                <div className="flex gap-2">

                  <button onClick={() => toggleAlert(alert.id, alert.active)}>
                    {alert.active ? (
                      <ToggleRight className="text-green-600" />
                    ) : (
                      <ToggleLeft />
                    )}
                  </button>

                  <button onClick={() => deleteAlert(alert.id)}>
                    <Trash2 size={16} />
                  </button>

                </div>

              </div>
            ))
          )}

        </div>
      </div>
    </AdminLayout>
  );
}
