'use client';

import { useEffect, useState } from 'react';
import { collection, getDocs, addDoc, updateDoc, deleteDoc, doc, serverTimestamp } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import AdminLayout from '@/components/AdminLayout';
import { Plus, Trash2, ToggleLeft, ToggleRight, Bell } from 'lucide-react';

const severityOptions = ['low', 'medium', 'high'];
const typeOptions = ['rain', 'wind', 'heat', 'humidity', 'drought', 'general'];

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ title: '', subtitle: '', severity: 'medium', type: 'general', location: '' });
  const [saving, setSaving] = useState(false);

  const fetchAlerts = async () => {
    const snap = await getDocs(collection(db, 'alerts'));
    setAlerts(snap.docs.map(d => ({ id: d.id, ...d.data() })));
    setLoading(false);
  };

  useEffect(() => { fetchAlerts(); }, []);

  const addAlert = async () => {
    if (!form.title) return;
    setSaving(true);
    const ref = await addDoc(collection(db, 'alerts'), {
      ...form,
      active: true,
      autoGenerated: false,
      createdAt: serverTimestamp(),
    });
    setAlerts(prev => [...prev, { id: ref.id, ...form, active: true, autoGenerated: false }]);
    setForm({ title: '', subtitle: '', severity: 'medium', type: 'general', location: '' });
    setShowForm(false);
    setSaving(false);
  };

  const toggleAlert = async (alertId: string, current: boolean) => {
    await updateDoc(doc(db, 'alerts', alertId), { active: !current });
    setAlerts(prev => prev.map(a => a.id === alertId ? { ...a, active: !current } : a));
  };

  const deleteAlert = async (alertId: string) => {
    if (!confirm('Delete this alert?')) return;
    await deleteDoc(doc(db, 'alerts', alertId));
    setAlerts(prev => prev.filter(a => a.id !== alertId));
  };

  const severityColor = (s: string) => {
    if (s === 'high') return 'badge-red';
    if (s === 'medium') return 'badge-yellow';
    return 'badge-blue';
  };

  return (
    <AdminLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="font-display text-2xl font-bold text-gray-900">Alerts</h1>
            <p className="text-gray-500 text-sm mt-1">{alerts.filter(a => a.active).length} active alerts</p>
          </div>
          <button onClick={() => setShowForm(true)} className="btn-primary flex items-center gap-2">
            <Plus size={16} /> New Alert
          </button>
        </div>

        {/* Add alert form */}
        {showForm && (
          <div className="card p-6">
            <h3 className="font-semibold text-gray-900 mb-4">Create Alert</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Title *</label>
                <input className="input" placeholder="🌧 Heavy Rain Expected" value={form.title}
                  onChange={e => setForm(p => ({ ...p, title: e.target.value }))} />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Location</label>
                <input className="input" placeholder="e.g. Occidental Mindoro" value={form.location}
                  onChange={e => setForm(p => ({ ...p, location: e.target.value }))} />
              </div>
              <div className="sm:col-span-2">
                <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                <input className="input" placeholder="Alert details..." value={form.subtitle}
                  onChange={e => setForm(p => ({ ...p, subtitle: e.target.value }))} />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Type</label>
                <select className="input" value={form.type}
                  onChange={e => setForm(p => ({ ...p, type: e.target.value }))}>
                  {typeOptions.map(t => <option key={t} value={t}>{t}</option>)}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Severity</label>
                <select className="input" value={form.severity}
                  onChange={e => setForm(p => ({ ...p, severity: e.target.value }))}>
                  {severityOptions.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
              </div>
            </div>
            <div className="flex gap-3 mt-4">
              <button onClick={addAlert} disabled={saving} className="btn-primary">
                {saving ? 'Creating...' : 'Create Alert'}
              </button>
              <button onClick={() => setShowForm(false)} className="btn-secondary">Cancel</button>
            </div>
          </div>
        )}

        {/* Alerts list */}
        <div className="space-y-3">
          {loading ? (
            <div className="card p-8 text-center text-gray-400">Loading alerts...</div>
          ) : alerts.length === 0 ? (
            <div className="card p-12 text-center">
              <Bell size={40} className="mx-auto text-gray-300 mb-3" />
              <p className="text-gray-500">No alerts yet. Create one above.</p>
            </div>
          ) : alerts.map((alert) => (
            <div key={alert.id} className={`card p-4 flex items-start gap-4 ${!alert.active ? 'opacity-60' : ''}`}>
              <div className={`w-2 h-2 rounded-full mt-2 flex-shrink-0 ${
                alert.severity === 'high' ? 'bg-red-500' :
                alert.severity === 'medium' ? 'bg-yellow-500' : 'bg-blue-500'
              }`} />
              <div className="flex-1 min-w-0">
                <div className="flex flex-wrap items-center gap-2 mb-1">
                  <p className="font-medium text-gray-900">{alert.title}</p>
                  <span className={severityColor(alert.severity)}>{alert.severity}</span>
                  <span className="badge-gray">{alert.type}</span>
                  {alert.autoGenerated && <span className="badge-blue">Auto</span>}
                  {alert.active ? <span className="badge-green">Active</span> : <span className="badge-gray">Inactive</span>}
                </div>
                {alert.subtitle && <p className="text-sm text-gray-500">{alert.subtitle}</p>}
                {alert.location && <p className="text-xs text-gray-400 mt-1">📍 {alert.location}</p>}
              </div>
              <div className="flex items-center gap-2 flex-shrink-0">
                <button onClick={() => toggleAlert(alert.id, alert.active)}
                  className="p-1.5 rounded-lg text-gray-400 hover:text-[#2E7D32] hover:bg-green-50 transition-colors"
                  title={alert.active ? 'Deactivate' : 'Activate'}>
                  {alert.active ? <ToggleRight size={20} className="text-[#2E7D32]" /> : <ToggleLeft size={20} />}
                </button>
                <button onClick={() => deleteAlert(alert.id)}
                  className="p-1.5 rounded-lg text-gray-400 hover:text-red-500 hover:bg-red-50 transition-colors">
                  <Trash2 size={16} />
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </AdminLayout>
  );
}
