// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATsC6VIVlxbsJUwAXQlJINFGXYCUsMKnQ',
    appId: '1:582501260092:web:f3ad4853057eb66bcb9c39',
    messagingSenderId: '582501260092',
    projectId: 'agrismart-f1548',
    authDomain: 'agrismart-f1548.firebaseapp.com',
    storageBucket: 'agrismart-f1548.firebasestorage.app',
    measurementId: 'G-X45ZVBNS6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq9hVKF3-7IlOVJFlR4snY1qA2io0QooM',
    appId: '1:582501260092:android:c50c3eae315f2ac4cb9c39',
    messagingSenderId: '582501260092',
    projectId: 'agrismart-f1548',
    storageBucket: 'agrismart-f1548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwpA7GP35ngwuwXczvJMeqFCcKeVmq9Co',
    appId: '1:582501260092:ios:83807c186f835cdfcb9c39',
    messagingSenderId: '582501260092',
    projectId: 'agrismart-f1548',
    storageBucket: 'agrismart-f1548.firebasestorage.app',
    androidClientId: '582501260092-n4cc5hn9ofuvnik6oe3a8eh5uukqqij9.apps.googleusercontent.com',
    iosClientId: '582501260092-8v7cfqopi22erols00ra0i3hod2ctno4.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrismartDev2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATsC6VIVlxbsJUwAXQlJINFGXYCUsMKnQ',
    appId: '1:582501260092:web:05a0522904f72e02cb9c39',
    messagingSenderId: '582501260092',
    projectId: 'agrismart-f1548',
    authDomain: 'agrismart-f1548.firebaseapp.com',
    storageBucket: 'agrismart-f1548.firebasestorage.app',
    measurementId: 'G-FRDME9NPZJ',
  );

}