import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_generative_ai/google_generative_ai.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:llama_flutter_android/llama_flutter_android.dart' as llama;
import 'app_state.dart';

class GuideGenerationService {
  static const List<Map<String, String>> _guideTypes = [
    {
      'category': 'Pest & Disease',
      'key': 'pest_disease',
      'prompt':
          'Write a practical guide on common pests and diseases affecting {variety} onions in the Philippines, '
              'currently at {stage} stage ({dap} days after planting). Include identification, prevention, and treatment. '
              'Keep it concise and actionable for smallholder farmers.',
    },
    {
      'category': 'Irrigation Tips',
      'key': 'irrigation',
      'prompt':
          'Write irrigation guidelines for {variety} onions at {stage} stage ({dap} days after planting) '
              'in the Philippines. Include frequency, water amounts, and tips for {irrigationType} farming. '
              'Keep it practical for smallholder farmers.',
    },
    {
      'category': 'Harvest Timing',
      'key': 'harvest',
      'prompt':
          'Write a harvest timing guide for {variety} onions in the Philippines. '
              'The crop is currently at {stage} stage ({dap} days after planting). '
              'Include signs of maturity, harvesting method, and post-harvest handling tips.',
    },
    {
      'category': 'General Variety Guide',
      'key': 'variety',
      'prompt':
          'Write a general farming guide for {variety} onions in the Philippines. '
              'Cover soil preparation, planting, fertilization, and common challenges. '
              'Keep it practical for smallholder farmers with {irrigationType} irrigation.',
    },
    {
      'category': 'Weather',
      'key': 'weather',
      'prompt':
          'Write weather management tips for {variety} onion farmers in the Philippines, '
              'currently at {stage} stage ({dap} days after planting). '
              'Cover how to protect crops from heavy rain, heat, and humidity. '
              'Keep advice practical for smallholder farmers.',
    },
  ];

  static String _getGrowthStage(DateTime plantingDate) {
    final dap = DateTime.now().difference(plantingDate).inDays;
    if (dap <= 14) return 'Germination';
    if (dap <= 30) return 'Seedling';
    if (dap <= 60) return 'Vegetative';
    if (dap <= 90) return 'Bulbing';
    if (dap <= 110) return 'Maturation';
    return 'Ready for Harvest';
  }

  static String _buildPrompt(
    Map<String, String> guideType, {
    required String variety,
    required String stage,
    required int dap,
    required String irrigationType,
  }) {
    return guideType['prompt']!
        .replaceAll('{variety}', variety)
        .replaceAll('{stage}', stage)
        .replaceAll('{dap}', dap.toString())
        .replaceAll('{irrigationType}', irrigationType);
  }

  static Future<bool> _guideExists(
      String userId, String fieldId, String guideKey) async {
    final snap = await FirebaseFirestore.instance
        .collection('articles')
        .where('autoGenerated', isEqualTo: true)
        .where('fieldId', isEqualTo: fieldId)
        .where('guideKey', isEqualTo: guideKey)
        .limit(1)
        .get();
    return snap.docs.isNotEmpty;
  }

  static Future<String?> _generateContent(String prompt) async {
    final isOnline = !AppState.forceOffline.value;

    if (isOnline) {
      try {
        final apiKey = dotenv.env['GEMINI_API_KEY'] ?? '';
        if (apiKey.isEmpty) return null;
        final model = GenerativeModel(
          model: 'gemini-2.5-flash',
          apiKey: apiKey,
        );
        final response = await model
            .generateContent([Content.text(prompt)]).timeout(
          const Duration(seconds: 30),
        );
        return response.text;
      } catch (e) {
        print('Gemini guide generation error: $e');
        // Fall through to local model if Gemini fails
      }
    }

    // Use preloaded local model (Gemma 2B GGUF) if available
    if (AppState.llamaLoaded && AppState.llamaController != null) {
      try {
        print('Using local Gemma 2B model for guide generation...');
        final buffer = StringBuffer();
        await for (final token in AppState.llamaController!.generateChat(
          messages: [
            llama.ChatMessage(
              role: 'system',
              content:
                  'You are an agricultural expert helping Filipino onion farmers. '
                  'Provide practical, concise advice suited to smallholder farmers.',
            ),
            llama.ChatMessage(role: 'user', content: prompt),
          ],
          temperature: 0.7,
          maxTokens: 512,
        )) {
          buffer.write(token);
        }
        return buffer.toString();
      } catch (e) {
        print('Gemma guide generation error: $e');
        return null;
      }
    }

    return null;
  }

  /// Main method — generate guides for all user fields on startup
  static Future<void> generateGuidesForUser({
    void Function(String status)? onProgress,
  }) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) return;

    // Skip if no API key and no local model
    final apiKey = dotenv.env['GEMINI_API_KEY'] ?? '';
    if (apiKey.isEmpty && !AppState.llamaLoaded) {
      print('No AI model available for guide generation');
      return;
    }

    try {
      final fieldsSnap = await FirebaseFirestore.instance
          .collection('users')
          .doc(user.uid)
          .collection('fields')
          .where('status', isEqualTo: 'active')
          .get();

      if (fieldsSnap.docs.isEmpty) return;

      for (final fieldDoc in fieldsSnap.docs) {
        final field = fieldDoc.data();
        final variety = field['variety'] as String? ?? 'onion';
        final irrigationType =
            field['irrigationType'] as String? ?? 'Irrigated';
        final plantingDate =
            (field['plantingDate'] as Timestamp?)?.toDate();
        if (plantingDate == null) continue;

        final dap = DateTime.now().difference(plantingDate).inDays;
        final stage = _getGrowthStage(plantingDate);

        for (final guideType in _guideTypes) {
          final guideKey = guideType['key']!;

          final exists =
              await _guideExists(user.uid, fieldDoc.id, guideKey);
          if (exists) continue;

          onProgress?.call(
              'Generating ${guideType['category']} guide for $variety...');

          final prompt = _buildPrompt(
            guideType,
            variety: variety,
            stage: stage,
            dap: dap,
            irrigationType: irrigationType,
          );

          final content = await _generateContent(prompt);
          if (content == null || content.isEmpty) continue;

          await FirebaseFirestore.instance
              .collection('articles')
              .add({
            'title':
                '${guideType['category']} Guide — $variety ($stage)',
            'summary':
                'Auto-generated guide for your $variety field at $stage stage.',
            'content': content,
            'category': guideType['category'],
            'published': true,
            'autoGenerated': true,
            'fieldId': fieldDoc.id,
            'userId': user.uid,
            'guideKey': guideKey,
            'variety': variety,
            'stage': stage,
            'createdAt': FieldValue.serverTimestamp(),
          });

          print(
              'Guide generated: ${guideType['category']} for $variety');
        }
      }

      onProgress?.call('Guides updated!');
    } catch (e) {
      print('Guide generation error: $e');
    }
  }
}